<!DOCTYPE html>
<html lang="<?php echo $this->lang; ?>">
    <head>
        <meta charset="<?php echo $this->charset; ?>">
        <meta name="keywords" content="<?php echo $this->keywords; ?>">
        <meta name="description" content="<?php echo $this->description; ?>">
        <title><?php echo $this->title; ?></title>
        <?php echo $this->getStylesheetsMarkup(); ?>
        <?php echo $this->getHeadScriptsMarkup(); ?>
    </head>
    <body>
        <?php echo $this->body ?>
        <?php echo $this->getBodyScriptsMarkup(); ?>
    </body>
</html>
